#!/bin/sh

astatus="$(echo "$(cat /etc/dorfmap/pw.powerswitch)" status | nc -w 4 helios 1338)"

AMPDIR=/tmp/helios1

for port in 0 1 2 3; do
	if echo "$astatus" | fgrep -q "port ${port}: on"; then
		echo 1 > ${AMPDIR}/${port}
	elif echo "$astatus" | fgrep -q "port ${port}: off"; then
		echo 0 > ${AMPDIR}/${port}
	else
		echo - -1 > ${AMPDIR}/${port}
	fi
done
