#!/bin/sh

#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	cat <<'EOF'
graph_title Raumstatus
graph_args -l -1 -u 2
graph_vlabel Raumstatus
graph_category network
graph_info 1 = offen, 0 = zu, -1 = unbekannt
status.label status
status.draw AREASTACK
status.info Raumstatus
status.min -1
status.max 1
shutdown.label is_shutdown
shutdown.draw AREASTACK
shutdown.info Status des Shutdown-Knopfs
shutdown.min -1
shutdown.max 1
EOF
	exit 0
fi

STATUS="$(cat /srv/www/doorstatus)"

case "${STATUS}" in
open*) echo status.value 1 ;;
closed*) echo status.value 0 ;;
*) echo status.value -1 ;;
esac

if [ -e /tmp/is_shutdown ]; then
	if curl -s -m 4 http://dorfmap/status/info.json | python -c \
			'import sys, json; sys.exit(json.load(sys.stdin)["powered_areas"] == 0)'; then
		echo shutdown.value 0.5
	else
		echo shutdown.value 1
	fi
else
	echo shutdown.value 0
fi
