#!/usr/bin/env perl

#%# family=auto
#%# capabilities=autoconf

use strict;
use warnings;
use 5.014;
use utf8;

use JSON;    # automatically uses JSON::XS if available
use LWP::Simple;

my $raw_json = get('http://mete/users/stats.json');
my $json = from_json($raw_json);

if ( @ARGV and $ARGV[0] eq 'autoconf' ) {
	if ($json) {
		say 'yes';
		exit 0;
	}
	say 'no (unable to find a running mete instance)';
	exit 0;
}

if ( @ARGV and $ARGV[0] eq 'config' ) {
	say 'graph_title METE magic';
	say 'graph_vlabel magic[tm]';
	say 'graph_info Magicn';
	say 'graph_category other';
	say 'magic.label magic';
	exit 0;
}

if (exists $json->{balance_sum}) {
	printf("magic.value %.2f\n", $json->{balance_sum});
}
