#!/bin/sh -e

tar -C /tmp -xf /root/gnupg.tar.xz

mkdir -p /srv/www/.ssh
cat > /srv/www/.ssh/known_hosts <<EOF
|1|cQGYDnnjiPooTNqa2nNgT4dF5ts=|Qx9VZj0XF/6/H8AdWK6opNDKZyg= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIdZeAnygRug1whpYgtXRyrwbxvvVTIy5arzNCQvAJuT63RU4QvCyqtHpNEBKYhnQtZt7Oq3p7R5h6WFICgFodo=
|1|bSeqXEwoOzLhfUwrKDCcw5Ja7rY=|bHBAjWp39PuC+YABZeVGKuZGgYw= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIdZeAnygRug1whpYgtXRyrwbxvvVTIy5arzNCQvAJuT63RU4QvCyqtHpNEBKYhnQtZt7Oq3p7R5h6WFICgFodo=
EOF
chown www-data:www-data /srv/www/.ssh /srv/www/.ssh/known_hosts
