#!/bin/sh -e

gpioexport() {
	echo "$1" > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio"$1"/direction
	chmod 666 /sys/class/gpio/gpio"$1"/value
}

tar -C /tmp -xf /root/gnupg.tar.xz

touch /tmp/automatic_logo /tmp/automatic_outdoor /tmp/is_shutdown
chown www-data:www-data /tmp/automatic_logo /tmp/automatic_outdoor /tmp/is_shutdown

gpioexport 20
gpioexport 21

mkdir /tmp/dorfmap-err
chmod 777 /tmp/dorfmap-err

mkdir /tmp/donationprint1
chmod 777 /tmp/donationprint1
for i in $(seq 1 13); do
	echo 0 > /tmp/donationprint1/$i
	chmod 666 /tmp/donationprint1/$i
done

mkdir /tmp/donationprint2
chmod 777 /tmp/donationprint2
for i in commands; do
	echo 0 > /tmp/donationprint2/$i
	chmod 666 /tmp/donationprint2/$i
done

mkdir /tmp/feedback1
chmod 777 /tmp/feedback1
for i in $(seq 1 13); do
	echo 0 > /tmp/feedback1/$i
	chmod 666 /tmp/feedback1/$i
done

mkdir /tmp/feedback3
chmod 777 /tmp/feedback3
for i in $(seq 1 12); do
	echo 0 > /tmp/feedback3/$i
	chmod 666 /tmp/feedback3/$i
done

mkdir /tmp/feedback4
chmod 777 /tmp/feedback4
for i in commands; do
	echo 0 > /tmp/feedback4/$i
	chmod 666 /tmp/feedback4/$i
done

mkdir /tmp/feedback5
chmod 777 /tmp/feedback5
for i in $(seq 1 8); do
	echo 0 > /tmp/feedback5/$i
	chmod 666 /tmp/feedback5/$i
done

mkdir /tmp/feedback6
chmod 777 /tmp/feedback6
for i in bin0 bin1 bin3 bin5 bin6 bin7 pwm0 pwm1 pwm2; do
	echo 0 > /tmp/feedback6/$i
	chmod 666 /tmp/feedback6/$i
done

mkdir /tmp/feedback7
chmod 777 /tmp/feedback7
for i in bin0 bin1 bin2 bin3 bin4 bin5 bin6 bin7 bin8 pwm0 pwm1 pwm2 pwm3; do
	echo 0 > /tmp/feedback7/$i
	chmod 666 /tmp/feedback7/$i
done

mkdir /tmp/feedback8
chmod 777 /tmp/feedback8
for i in bin0 bin1 bin2 bin3 bin4 bin5 bin6 bin7 bin8 pwm0 pwm1 pwm2 pwm3; do
	echo 0 > /tmp/feedback8/$i
	chmod 666 /tmp/feedback8/$i
done

mkdir /tmp/feedback9
chmod 777 /tmp/feedback9
for i in bin0 bin1 bin2 bin3 bin4 bin5 bin6 bin7 bin8 pwm0 pwm1 pwm2 pwm3; do
	echo 0 > /tmp/feedback9/$i
	chmod 666 /tmp/feedback9/$i
done

mkdir /tmp/feedback10
chmod 777 /tmp/feedback10
for i in bin0 bin1 bin2 bin3 bin4 bin5 bin6 pwm0 pwm1 pwm2 pwm3; do
	echo 0 > /tmp/feedback10/$i
	chmod 666 /tmp/feedback10/$i
done

mkdir /tmp/helios1
chmod 777 /tmp/helios1
for i in 0 1 2 3; do
	echo 0 > /tmp/helios1/$i
	chmod 666 /tmp/helios1/$i
done

dorfmap_get_amps

if [ -e /boot/dorfmapstate.tar.xz ]; then
	tar -C / -xJf /boot/dorfmapstate.tar.xz
	rm /boot/dorfmapstate.tar.xz
fi

mkdir -p /srv/www/.ssh
cat > /srv/www/.ssh/known_hosts <<EOF
|1|cQGYDnnjiPooTNqa2nNgT4dF5ts=|Qx9VZj0XF/6/H8AdWK6opNDKZyg= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIdZeAnygRug1whpYgtXRyrwbxvvVTIy5arzNCQvAJuT63RU4QvCyqtHpNEBKYhnQtZt7Oq3p7R5h6WFICgFodo=
|1|bSeqXEwoOzLhfUwrKDCcw5Ja7rY=|bHBAjWp39PuC+YABZeVGKuZGgYw= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIdZeAnygRug1whpYgtXRyrwbxvvVTIy5arzNCQvAJuT63RU4QvCyqtHpNEBKYhnQtZt7Oq3p7R5h6WFICgFodo=
EOF
chown www-data:www-data /srv/www/.ssh /srv/www/.ssh/known_hosts

cd /srv/www
rsync -a /root/dorfmap/ dorfmap/
cd dorfmap
chown -R www-data:www-data .
nice -n -1 sudo -u www-data hypnotoad index.pl

if [ -e /boot/dorfmap-presets.db ]; then
	cat /boot/dorfmap-presets.db > /srv/www/dorfmap/presets.db
	chown www-data:www-data /srv/www/dorfmap/presets.db
fi
if [ -e /boot/dorfmap-blinkencontrol.db ]; then
	cat /boot/dorfmap-blinkencontrol.db > /srv/www/dorfmap/blinkencontrol.db
	chown www-data:www-data /srv/www/dorfmap/blinkencontrol.db
fi
