#!/bin/sh

if [ -e /tmp/is_shutdown ]; then
	echo 0 > /sys/class/gpio/gpio17/value
	echo 0 > /tmp/feedback2/pwm2
else
	if [ -e /tmp/automatic_outdoor ]; then
		is_sundown -o -d $(cat /etc/automatic_light_control/outdoor) \
			> /sys/class/gpio/gpio17/value
	else
		echo 0 > /sys/class/gpio/gpio17/value
	fi
	if [ -e /tmp/automatic_logo ]; then
		is_sundown -o -d $(cat /etc/automatic_light_control/logo) \
			> /tmp/feedback2/pwm2
	else
		echo 0 > /tmp/feedback2/pwm2
	fi
fi

if [ -e /tmp/automatic_schaufenster ]; then
	is_sundown -o -d $(cat /etc/automatic_light_control/schaufenster) \
		> /tmp/feedback2/bin1
else
	echo 0 > /tmp/feedback2/bin1
fi

avrshift-feedback
