#!/bin/sh

(
echo '    halt' > /tmp/feedback1/7segment3.mode
echo '    halt' > /tmp/feedback1/7segment2.mode
echo '    halt' > /tmp/donationprint1/7segment1.mode

update_clocks
) &

dorfmap-savedata

sleep 2

exec halt
