#!/bin/sh

export PATH="/usr/local/bin:$PATH"

read line;

if [ "${line}" = "$(cat /etc/dorfmap/pw.bell)" ]; then

	echo 1 > /tmp/feedback1/13
	dorfmap_set_remote feedback1

	(
	sleep 12
	echo 0 > /tmp/feedback1/13
	dorfmap_set_remote feedback1
	) &

	if [ -z "$RANDOM" ]; then
		RANDOM=$(dd if=/dev/urandom count=1 2> /dev/null | cksum | cut -c"1-5")
	fi

	case $(( RANDOM % 6 )) in
		0) BFILE=doorbell1.wav ;;
		1) BFILE=doorbell1.wav ;;
		2) BFILE=doorbell2.m4a ;;
		3) BFILE=doorbell3.ogg ;;
		4) BFILE=doorbell4.mp3 ;;
		5) BFILE=doorbell5.m4a ;;
	esac

	mosquitto_pub -h mqttserver -t 'space/bell' -m ringdingding &

	flock -n /tmp/ringbellmp.lock mplayer -ao pulse:pulseaudio /usr/local/share/"${BFILE}" < /dev/null > /dev/null 2> /dev/null || exit 1

elif [ "${line}" = openannounce ]; then

	echo open > /srv/www/doorstatus

	curl -s -m 4 -d action=shortcut -d shortcut=unshutdown http://dorfmap/action

	echo 1 > /tmp/feedback8/bin8
	dorfmap_set_remote feedback8

	if [ -z "$RANDOM" ]; then
		RANDOM=$(dd if=/dev/urandom count=1 2> /dev/null | cksum | cut -c"1-5")
	fi

	case $(( RANDOM % 2 )) in
		0) AFILE=public.wav ;;
		1) AFILE=public2.wav ;;
	esac

	mosquitto_pub -h mqttserver -r -t 'door/status' -m open &

	mplayer -volume 100 -ao pulse:pulseaudio /usr/local/share/"${AFILE}" < /dev/null > /dev/null 2> /dev/null

elif [ "${line}" = closedannounce ]; then

	echo closed > /srv/www/doorstatus

	echo 0 > /tmp/feedback8/bin8
	dorfmap_set_remote feedback8

	if [ -z "$RANDOM" ]; then
		RANDOM=$(dd if=/dev/urandom count=1 2> /dev/null | cksum | cut -c"1-5")
	fi

	case $(( RANDOM % 2 )) in
		0) AFILE=private.wav ;;
		1) AFILE=private2.wav ;;
	esac

	mosquitto_pub -h mqttserver -r -t 'door/status' -m closed &

	mplayer -volume 100 -ao pulse:pulseaudio /usr/local/share/"${AFILE}" < /dev/null > /dev/null 2> /dev/null

elif [ "${line}" = donationprint_doorstatus ]; then

	curl -s -m 4 -d action=shortcut -d shortcut=makeprivate http://dorfmap/action

elif [ "${line}" = donationprint_raumstatus ]; then

	if [ -e /tmp/is_shutdown ]; then
		curl -s -m 4 -d action=shortcut -d shortcut=unshutdown http://dorfmap/action
	else
		curl -s -m 4 -d action=shortcut -d shortcut=shutdown http://dorfmap/action
	fi

fi

exit 0
