#!/bin/sh

#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi


# counter.type COUNTER makes munin use the difference to the previous reading,
# so we get the usage count for the last 5 minutes. however, since munin
# treats it as a per-second value, it is internally divided by 300
# (we refresh every 300 seconds). Therefore, we use .cdef with *3600 to
# turn it into a per-hour estimate.

if [ "$1" = "config" ]; then
	cat <<'EOF'
graph_title Chaosdoor
graph_args -l 0
graph_vlabel Oeffnungen / Stunde
graph_category network
graph_info Gemittelte Oeffnungen pro Stunde
counter.label usage
counter.info Tuerbetaetigungen / Stunde
counter.draw LINE1
counter.min 0
EOF
	exit 0
fi

COUNTER="$(cat /srv/www/bgdata/chaosdoor_diff || echo 0)"

echo counter.value "${COUNTER}"
