#!/bin/sh

#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	cat <<'EOF'
graph_title Raumstatus
graph_args -l -1 -u 2
graph_vlabel Raumstatus
graph_category network
graph_info 1 = offen, 0 = zu, -1 = unbekannt
status.label status
status.draw AREASTACK
status.info Raumstatus
status.min -1
status.max 1
shutdown.label is_shutdown
shutdown.draw AREASTACK
shutdown.info Status des Shutdown-Knopfs
shutdown.min -1
shutdown.max 1
EOF
	exit 0
fi

STATUS="$(cat /srv/www/doorstatus)"

case "${STATUS}" in
open*) echo status.value 1 ;;
closed*) echo status.value 0 ;;
*) echo status.value -1 ;;
esac

echo shutdown.value "$(cat /srv/www/is_shutdown || echo -1)"
