#!/bin/sh

#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then

	echo 'graph_title space temperatures'
	echo 'graph_vlabel deg C'
	echo 'graph_category sensors'
	echo 'lounge.label Lounge'

	exit 0
fi

LOUNGE="$(cat /srv/www/bgdata/lounge_screen_temp)"

if [ -z "$LOUNGE" ]; then
	return 0
fi

echo lounge.value "$LOUNGE"
