#!/bin/sh

#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then

	echo 'graph_title brightness'
	echo 'graph_vlabel Lux'
	echo 'graph_category sensors'
	echo 'window.label Fenster'

	exit 0
fi

WINDOW="$(cat /srv/www/mqtt/window.lux)"

if [ -n "$WINDOW" ]; then
	echo window.value "$WINDOW"
fi
