#!/bin/sh

#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then

	echo 'graph_title space brightness'
	echo 'graph_vlabel relative brightness'
	echo 'graph_category sensors'
	echo 'lounge.label Lounge'
	echo 'hackcenter.label Hackcenter'

	exit 0
fi

LOUNGE="$(cat /srv/www/bgdata/lounge_screen_brightness)"
HACKCENTER="$(cat /srv/www/bgdata/hackcenter_brightness)"

if [ -n "$LOUNGE" ]; then
	echo lounge.value "$LOUNGE"
fi
if [ -n "$HACKCENTER" ]; then
	echo hackcenter.value "$HACKCENTER"
fi
