#!/bin/sh

#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then

	echo 'graph_title space temperatures'
	echo 'graph_vlabel deg C'
	echo 'graph_category sensors'
	echo 'lounge.label Lounge'
	echo 'hackcenter.label Hackcenter'
	echo 'serverraum.label Serverraum'
	echo 'maschinenraum.label Maschinenraum'

	exit 0
fi

LOUNGE="$(cat /srv/www/bgdata/lounge_screen_temp)"
HACKCENTER="$(cat /srv/www/bgdata/hackcenter_temp)"
SERVERRAUM="$(cat /srv/www/mqtt/serverraum.degc)"
MASCHINENRAUM="$(cat /srv/www/bgdata/maschinenraum_temp)"

if [ -n "$LOUNGE" ]; then
	echo lounge.value "$LOUNGE"
fi
if [ -n "$HACKCENTER" ]; then
	echo hackcenter.value "$HACKCENTER"
fi
if [ -n "$SERVERRAUM" ]; then
	echo serverraum.value "$SERVERRAUM"
fi
if [ -n "$MASCHINENRAUM" ]; then
	echo Maschinenraum.value "$MASCHINENRAUM"
fi
