#!/bin/sh

#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	cat <<'EOF'
graph_title Online Hosts
graph_args -l 0
graph_vlabel Online Hosts
graph_category network
graph_info This graph shows the number of visible hosts
hosts.label Online Hosts
hosts.draw LINE1
hosts.info Current number of online hosts
dynip.label DHCP
dynip.draw STACK
dynip.info Hosts in dynamic DHCP range
static.label Static
static.draw STACK
static.info Hosts in static DHCP range
infra.label Management VLAN
infra.draw STACK
infra.info Hosts in Management VLAN
EOF
	exit 0
fi

echo "hosts.value $(cat /srv/www/bgdata/hosts_total)"
echo "dynip.value $(cat /srv/www/bgdata/hosts_dynamic)"
echo "static.value $(cat /srv/www/bgdata/hosts_static)"
echo "infra.value $(cat /srv/www/bgdata/hosts_management)"
