#!/bin/sh

#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
    cat <<'EOF'
graph_title Leistung
graph_vlabel W
graph_category other
graph_info Aktuell umgesetzte Leistung
phase1.label Phase 1
phase1.draw AREASTACK
phase1.info Hauptversorgung Phase 1
phase2.label Phase 2
phase2.draw AREASTACK
phase2.info Hauptversorgung Phase 2
phase3.label Phase 3
phase3.draw AREASTACK
phase3.info Hauptversorgung Phase 3
uvtotal.label Gesamt
uvtotal.draw LINE
uvtotal.info Hauptversorgung gesamt
EOF
    exit 0
fi

PHASE1="$(cat /srv/www/flukso/300_p1)"
PHASE2="$(cat /srv/www/flukso/300_p2)"
PHASE3="$(cat /srv/www/flukso/300_p3)"

echo phase1.value ${PHASE1}
echo phase2.value ${PHASE2}
echo phase3.value ${PHASE3}
echo -n uvtotal.value\ 
echo "${PHASE1} + ${PHASE2} + ${PHASE3}" | bc
